"""Human-friendly local workflow around the installed FaultNav CLI."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MINIMUM_PYTHON = (3, 10)
CI_PYTHON_MAXIMUM = (3, 12)
SETUP_INPUTS = ("pyproject.toml", "setup.py", "dev-requirements.txt")
MARKER_NAME = ".faultnav-setup.json"
DEMO_RELATIVE_DIR = Path("artifacts") / "demo"
DEMO_ARTIFACT_NAMES = (
    "figure_eight_combined_faults_sensor.csv",
    "figure_eight_combined_faults_sensor_metrics.json",
    "figure_eight_combined_faults_sensor_report.svg",
)


class WorkflowError(RuntimeError):
    """Failure that should be presented without a Python traceback."""


@dataclass(frozen=True)
class DoctorCheck:
    """One human-readable environment diagnostic."""

    label: str
    status: str
    detail: str
    required: bool = False


def venv_python_path(venv_dir: Path, platform_name: str | None = None) -> Path:
    """Return the virtual-environment interpreter path for one platform."""

    resolved_platform = platform_name if platform_name is not None else os.name
    if resolved_platform == "nt":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def venv_cli_path(venv_dir: Path, platform_name: str | None = None) -> Path:
    """Return the installed FaultNav experiment command path."""

    resolved_platform = platform_name if platform_name is not None else os.name
    if resolved_platform == "nt":
        return venv_dir / "Scripts" / "faultnav-experiment.exe"
    return venv_dir / "bin" / "faultnav-experiment"


def resolved_venv_dir(project_root: Path) -> Path:
    """Resolve an optional developer override or the standard ``.venv`` path."""

    configured = os.environ.get("FAULTNAV_VENV_DIR")
    if configured:
        candidate = Path(configured).expanduser()
        if not candidate.is_absolute():
            candidate = project_root / candidate
        return candidate.resolve()
    return project_root / ".venv"


def setup_fingerprint(project_root: Path, python_version: tuple[int, int]) -> str:
    """Hash environment-defining files so repeated setup can skip unchanged work."""

    digest = hashlib.sha256(f"python={python_version[0]}.{python_version[1]}\n".encode())
    for relative_path in SETUP_INPUTS:
        source = project_root / relative_path
        if not source.is_file():
            raise WorkflowError(f"Required setup file is missing: {source}")
        digest.update(f"file={relative_path}\n".encode())
        digest.update(source.read_bytes())
    return digest.hexdigest()


def expected_demo_artifacts(output_dir: Path) -> tuple[Path, ...]:
    """Return the deterministic artifact set generated by the main demo."""

    return tuple(output_dir / name for name in DEMO_ARTIFACT_NAMES)


def verify_demo_artifacts(output_dir: Path) -> tuple[Path, ...]:
    """Require every expected demo artifact to exist and be non-empty."""

    artifacts = expected_demo_artifacts(output_dir)
    missing = [path for path in artifacts if not path.is_file() or path.stat().st_size == 0]
    if missing:
        missing_names = ", ".join(path.name for path in missing)
        raise WorkflowError(f"Demo did not create the expected non-empty files: {missing_names}")
    return artifacts


def demo_command(cli_path: Path, output_dir: Path) -> list[str]:
    """Build the deterministic installed-CLI command used by ``RUN``."""

    return [
        str(cli_path),
        "--scenario",
        "figure-eight",
        "--step",
        "0.1",
        "--sensor-profile",
        "combined-faults",
        "--seed",
        "7",
        "--output-dir",
        str(output_dir),
    ]


def format_doctor_check(check: DoctorCheck) -> str:
    """Format a stable diagnostic row for technical and non-technical users."""

    return f"{check.label:.<28} {check.status:<4} {check.detail}"


def sanitized_remote_url(remote_url: str) -> str:
    """Remove credentials, query strings, and fragments from a displayed Git remote."""

    if "://" not in remote_url:
        return remote_url
    parsed = urlsplit(remote_url)
    hostname = parsed.hostname or "unknown-host"
    if ":" in hostname and not hostname.startswith("["):
        hostname = f"[{hostname}]"
    netloc = hostname if parsed.port is None else f"{hostname}:{parsed.port}"
    return urlunsplit((parsed.scheme, netloc, parsed.path, "", ""))


def _python_version_text() -> str:
    return ".".join(str(part) for part in sys.version_info[:3])


def _validate_system_python() -> None:
    version = sys.version_info[:2]
    if version < MINIMUM_PYTHON:
        required = ".".join(str(part) for part in MINIMUM_PYTHON)
        raise WorkflowError(
            f"Python {required} or newer is required; detected {_python_version_text()}.\n\n"
            "Install a supported Python version and enable 'Add Python to PATH', then try again."
        )
    if version > CI_PYTHON_MAXIMUM:
        maximum = ".".join(str(part) for part in CI_PYTHON_MAXIMUM)
        print(
            f"WARNING: Python {_python_version_text()} is newer than the validated CI range "
            f"(through {maximum}).",
            flush=True,
        )


def _run_visible(command: list[str], project_root: Path, description: str) -> None:
    print(f"\n{description}", flush=True)
    completed = subprocess.run(command, cwd=project_root, check=False)
    if completed.returncode != 0:
        raise WorkflowError(
            f"{description} failed with exit code {completed.returncode}.\n"
            "Review the messages above, then run DOCTOR for environment diagnostics."
        )


def _run_captured(
    command: list[str],
    project_root: Path,
    *,
    timeout_s: float = 10.0,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=project_root,
        check=False,
        capture_output=True,
        text=True,
        timeout=timeout_s,
    )


def _environment_imports_succeed(venv_python: Path, project_root: Path) -> bool:
    if not venv_python.is_file():
        return False
    command = [
        str(venv_python),
        "-c",
        "import faultnav_robot, numpy, pytest, ruff",
    ]
    try:
        return _run_captured(command, project_root).returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _marker_matches(
    marker_path: Path,
    project_root: Path,
    python_version: tuple[int, int],
) -> bool:
    try:
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return False
    return marker.get("fingerprint") == setup_fingerprint(project_root, python_version)


def _write_setup_marker(
    marker_path: Path,
    project_root: Path,
    python_version: tuple[int, int],
) -> None:
    marker = {
        "fingerprint": setup_fingerprint(project_root, python_version),
        "python": f"{python_version[0]}.{python_version[1]}",
    }
    marker_path.write_text(json.dumps(marker, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def environment_is_ready(project_root: Path, venv_dir: Path) -> bool:
    """Return whether setup inputs, imports, and the installed CLI are ready."""

    venv_python = venv_python_path(venv_dir)
    return (
        venv_cli_path(venv_dir).is_file()
        and _marker_matches(venv_dir / MARKER_NAME, project_root, sys.version_info[:2])
        and _environment_imports_succeed(venv_python, project_root)
    )


def setup_environment(project_root: Path = PROJECT_ROOT) -> Path:
    """Create or refresh the repository-local environment idempotently."""

    _validate_system_python()
    venv_dir = resolved_venv_dir(project_root)
    venv_python = venv_python_path(venv_dir)
    print(
        f"FaultNav local setup\nProject: {project_root}\nPython:  {_python_version_text()}",
        flush=True,
    )

    if venv_python.is_file():
        print(f"Virtual environment detected: {venv_dir}")
    elif venv_dir.exists():
        raise WorkflowError(
            f"The virtual-environment directory exists but is incomplete: {venv_dir}\n"
            "Move or remove that directory manually, then run SETUP again."
        )
    else:
        _run_visible(
            [sys.executable, "-m", "venv", str(venv_dir)],
            project_root,
            "Creating the virtual environment...",
        )

    if environment_is_ready(project_root, venv_dir):
        print("Dependencies and editable package are already installed and current.")
        print("\nEnvironment ready. Run RUN.bat (Windows) or sh run.sh (Linux/macOS).")
        return venv_dir

    _run_visible(
        [str(venv_python), "-m", "pip", "install", "--upgrade", "pip"],
        project_root,
        "Updating pip inside the virtual environment...",
    )
    _run_visible(
        [
            str(venv_python),
            "-m",
            "pip",
            "install",
            "-e",
            ".",
            "-r",
            "dev-requirements.txt",
        ],
        project_root,
        "Installing FaultNav and development tools...",
    )
    if not _environment_imports_succeed(venv_python, project_root):
        raise WorkflowError(
            "Package verification failed after installation. Run DOCTOR for details."
        )
    if not venv_cli_path(venv_dir).is_file():
        raise WorkflowError("The installed faultnav-experiment command was not found after setup.")
    _write_setup_marker(venv_dir / MARKER_NAME, project_root, sys.version_info[:2])
    print("\nEnvironment ready. Run RUN.bat (Windows) or sh run.sh (Linux/macOS).")
    return venv_dir


def ensure_environment(project_root: Path) -> Path:
    """Reuse a ready environment or perform the documented setup automatically."""

    venv_dir = resolved_venv_dir(project_root)
    if environment_is_ready(project_root, venv_dir):
        return venv_dir
    print("FaultNav is not set up yet, so setup will run first.", flush=True)
    return setup_environment(project_root)


def run_demo(project_root: Path = PROJECT_ROOT) -> tuple[Path, ...]:
    """Run the deterministic combined-fault demonstration through the installed CLI."""

    venv_dir = ensure_environment(project_root)
    output_dir = project_root / DEMO_RELATIVE_DIR
    command = demo_command(venv_cli_path(venv_dir), output_dir)
    _run_visible(command, project_root, "Running the deterministic FaultNav demonstration...")
    artifacts = verify_demo_artifacts(output_dir)
    report_path = output_dir / "figure_eight_combined_faults_sensor_report.svg"
    print("\nDemo completed successfully.")
    print(f"Results folder: {output_dir}")
    print(f"Open this report in a web browser: {report_path}")
    print("These are deterministic simulation results, not physical-robot measurements.")
    return artifacts


def run_tests(project_root: Path = PROJECT_ROOT) -> None:
    """Run the documented lint and Python test commands in the managed environment."""

    venv_dir = ensure_environment(project_root)
    venv_python = venv_python_path(venv_dir)
    _run_visible(
        [
            str(venv_python),
            "-m",
            "ruff",
            "check",
            "src",
            "tests",
            "scripts",
            "setup.py",
            "launch",
        ],
        project_root,
        "Running Ruff...",
    )
    _run_visible(
        [str(venv_python), "-m", "pytest"],
        project_root,
        "Running pytest...",
    )
    print("\nAll FaultNav Python checks passed.")


def _doctor_python_check() -> DoctorCheck:
    version = sys.version_info[:2]
    detail = _python_version_text()
    if version < MINIMUM_PYTHON:
        return DoctorCheck("Python", "FAIL", f"{detail}; Python 3.10+ required", True)
    if version > CI_PYTHON_MAXIMUM:
        return DoctorCheck("Python", "WARN", f"{detail}; CI validates 3.10-3.12")
    return DoctorCheck("Python", "OK", detail, True)


def run_doctor(project_root: Path = PROJECT_ROOT) -> int:
    """Print actionable local environment, Git, and GitHub diagnostics."""

    checks = [_doctor_python_check()]
    venv_dir = resolved_venv_dir(project_root)
    venv_python = venv_python_path(venv_dir)
    if venv_python.is_file():
        checks.append(DoctorCheck("Virtual environment", "OK", str(venv_dir), True))
    else:
        checks.append(DoctorCheck("Virtual environment", "FAIL", "run SETUP first", True))

    if _environment_imports_succeed(venv_python, project_root):
        checks.append(DoctorCheck("Package and dependencies", "OK", "imports succeeded", True))
    else:
        checks.append(
            DoctorCheck("Package and dependencies", "FAIL", "run SETUP to install", True)
        )
    if venv_cli_path(venv_dir).is_file():
        checks.append(DoctorCheck("Installed CLI", "OK", "faultnav-experiment", True))
    else:
        checks.append(DoctorCheck("Installed CLI", "FAIL", "run SETUP to install", True))

    output_parent = project_root / "artifacts"
    writable_target = output_parent if output_parent.exists() else project_root
    if os.access(writable_target, os.W_OK):
        checks.append(DoctorCheck("Writable output", "OK", str(output_parent), True))
    else:
        checks.append(DoctorCheck("Writable output", "FAIL", str(writable_target), True))

    git_path = shutil.which("git")
    git_repository = False
    if git_path is None:
        checks.append(DoctorCheck("Git", "WARN", "not found; demo still works"))
    else:
        repository_check = _run_captured(
            [git_path, "rev-parse", "--is-inside-work-tree"], project_root
        )
        git_repository = repository_check.returncode == 0
        status = "OK" if git_repository else "WARN"
        detail = "repository detected" if git_repository else "not a Git checkout"
        checks.append(DoctorCheck("Git repository", status, detail))

    if git_repository and git_path is not None:
        branch = _run_captured([git_path, "branch", "--show-current"], project_root)
        branch_name = branch.stdout.strip() or "detached HEAD"
        checks.append(DoctorCheck("Current branch", "OK", branch_name))

        remote = _run_captured([git_path, "remote", "get-url", "origin"], project_root)
        if remote.returncode == 0 and remote.stdout.strip():
            checks.append(
                DoctorCheck("Git origin", "OK", sanitized_remote_url(remote.stdout.strip()))
            )
            try:
                connection = _run_captured(
                    [git_path, "ls-remote", "--exit-code", "origin", "HEAD"],
                    project_root,
                    timeout_s=10.0,
                )
                connection_ok = connection.returncode == 0
            except subprocess.TimeoutExpired:
                connection_ok = False
            connection_status = "OK" if connection_ok else "WARN"
            connection_detail = "reachable" if connection_ok else "unavailable or offline"
            checks.append(DoctorCheck("GitHub connection", connection_status, connection_detail))
        else:
            checks.append(DoctorCheck("Git origin", "WARN", "origin is not configured"))

        worktree = _run_captured([git_path, "status", "--short"], project_root)
        change_count = len([line for line in worktree.stdout.splitlines() if line.strip()])
        if change_count:
            checks.append(
                DoctorCheck(
                    "Working tree",
                    "WARN",
                    f"{change_count} local change(s); review before push",
                )
            )
        else:
            checks.append(DoctorCheck("Working tree", "OK", "clean"))

    print("FaultNav environment doctor\n")
    for check in checks:
        print(format_doctor_check(check))
    failures = [check for check in checks if check.required and check.status == "FAIL"]
    if failures:
        print("\nERROR: Required checks failed. Follow the messages above, then run DOCTOR again.")
        return 1
    print("\nRequired local checks passed. WARN items do not block the Python demonstration.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    """Build the internal workflow parser used by the root launchers."""

    parser = argparse.ArgumentParser(description="FaultNav local setup and demonstration helper.")
    parser.add_argument("action", choices=("setup", "run", "test", "doctor"))
    return parser


def main(args: list[str] | None = None) -> int:
    """Execute one user-facing local workflow with concise error handling."""

    parsed = build_parser().parse_args(args)
    try:
        if parsed.action == "setup":
            setup_environment()
        elif parsed.action == "run":
            run_demo()
        elif parsed.action == "test":
            run_tests()
        else:
            return run_doctor()
    except WorkflowError as error:
        print(f"\nERROR: {error}", file=sys.stderr)
        return 1
    except (OSError, subprocess.TimeoutExpired) as error:
        print(f"\nERROR: A local command could not be completed: {error}", file=sys.stderr)
        print("Run DOCTOR for environment diagnostics.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
